### ISSUE TITLE
Allow visualization preferences to be communicated through API

### ISSUE THREAD

**Issue by Knoop** [2IMN00-16/backend#2]
To allow the visualization to be set, I would like to be able to control the visualization settings by sending a JSONObject with the following properties:

- **CycleRate** _Integer_ The amount of time, in milliseconds, each task should be visible for on a light if that light must visualize multiple tasks.
- **TimeFactor** _Integer_ The amount of time, in milliseconds, that is indicated by an unit less increment in the schedule.  If a schedule specifies a time `x`, then this should be interpreted as `x * TimeFactor` milliseconds. 
- **Lights** _JSONObject_ This maps the name of lights to the name of a visualization function. This is presented as a key to value mapping in the form of a JSONObject. The keys are taken from the "get lights" part of the API. The visualization function would be taken from the "get visualization functions" (see #1) part of the API. For lights that are not needed (off) I can either leave them out of the JSONObject or mention them as "off". From my perspective it would be even better if "off" was included as a visualization function, as this would mean the app does not have to handle special cases. 

I have no preference as to what URL this needs to be accessible on.

**Comment by Knoop** [comment]
To make integration easier I'll make my request more concrete.
Using the array from the initial commit:
I visit https://seminar.tuupke.nl/visualization and I provide 
```
{
    "CycleRate":1000, 
    "TimeFactor": 50,
    "lights": {
        "lamp 1" : "off",
        "lamp 2" : "Active",
        "lamp 3" : "Preempted"
     }
}
```
Note that I'll only use values that were returned to me by #1 to map lights to a visualization. The value is provided as the "data", as you have defined it on Server.POST in my android repository.

**Comment by tuupke** [comment]
It is going to be implemented differently:


    {
        "CycleRate":1000, 
        "TimeFactor": 50,
        "lights": [
            {
                "Name" : "lamp 1",
                "Value" : "off"
            },
            {
                "Name" : "lamp 2",
                "Value" : "Active"
            },
            {
                "Name" : "lamp 3",
                "Value" : "Preempted"
            }
        ]
    }

Since otherwise I cannot parse a different number than 3 lamps properly

**Comment by tuupke** [comment]
Will be merged with settings on the settings endpoint, final json looks like:

    {
        "CycleRate": 1000,
        "TimeFactor": 50,
        "Scheduler": "Preemtive",
        "Lights": [
            {
                "Name": "lamp1",
                "Value": "free"
            },
            {
                "Name": "lamp2",
                "Value": "free"
            },
            {
                "Name": "lamp3",
                "Value": "free"
            }
        ]
    }
