### ISSUE TITLE
Request: Make API provide a list of supported schedulers

### ISSUE THREAD

**Issue by Knoop** [2IMN00-16/backend#3]
Similar to #1, I would like to be able to obtain a JSONArray containing the names of all schedulers that are supported by the server. For all I care it could just be a static array containing "FPPS","FPTS" and "FPNS". I would just prefer not to have to define this as something static in the app.

I have no preference as to what URL this needs to be accessible on.

**Comment by Knoop** [comment]
To make integration easier I'll make my request more concrete.
Using the array from the initial commit:
If I visit https://seminar.tuupke.nl/schedulers I expect `["FPPS", "FPTS", "FPNS"]`.

**Comment by tuupke** [comment]
Actually, these settings already existed and the endpoint is using them now, so the returned array is: `["Non-Preemptive","Preemtive","Threshold"]`

**Comment by tuupke** [comment]
Was closed with wrong commit. Endpoint for this will be `https://seminar.tuupke.nl/settings/visualizers`

**Comment by Knoop** [comment]
The link mentioned by @tuupke (https://seminar.tuupke.nl/settings/visualizers) is wrong. Should be the link as specified by me (https://seminar.tuupke.nl/schedulers).
