### ISSUE TITLE
Request: Allow me to set the scheduler

### ISSUE THREAD

**Issue by Knoop** [2IMN00-16/backend#4]
I want to be able to set the scheduler by means of calling https://seminar.tuupke.nl/scheduler. I'll provide a value that was given to me by #3. In case the schedulers change between this call and my call to #3, you should be able to handle that. The value is provided as the "data", as you have defined it on `Server.POST` in my android repository.

**Comment by tuupke** [comment]
Allready existing functionality, but has been changed as described in #2
